[[chain]]
id = "testing"
key_format = { type = "bech32", account_key_prefix = "kirapub", consensus_key_prefix = "kiravalconspub" }

## Validator configuration
[[validator]]
addr = "tcp://10.2.0.2:12345"
chain_id = "testing"
reconnect = true
secret_key = "/root/.tmkms/secret_connection.key"
protocol_version = "v0.34"

## Signing provider configuration
[[providers.softsign]]
chain_ids = ["testing"]
key_type = "consensus"
path = "/root/.tmkms/signing.key"
