[[chain]]
id = "testing"
key_format = { type = "bech32", account_key_prefix = "kirapub", consensus_key_prefix = "kiravalconspub" }

## Validator configuration
[[validator]]
addr = "tcp://10.2.0.1:26658"
chain_id = "testing"
reconnect = true
secret_key = "~/.tmkms/secret_connection.key"

## Signing provider configuration
## [[providers.softsign]]
## chain_ids = ["testing"]
## key_format = "base64"
## path = "~/.tmkms/gaia_signing.key"
